CREATE TABLE voivodship(
	gid serial PRIMARY KEY,
	jpt_sjr_ko varchar(3),
	jpt_kod_je varchar(20),
	jpt_nazwa_ varchar(128),
	jpt_organ_ varchar(254),
	jpt_jor_id integer,
	wersja_od date,
	wersja_do date,
	wazny_od date,
	wazny_do date,
	jpt_kod__1 varchar(3),
	jpt_nazwa1 varchar(3),
	jpt_organ1 varchar(3),
	jpt_wazna_ varchar(3),
	id_bufora_ numeric,
	id_bufora1 numeric,
	id_technic integer,
	iip_przest varchar(20),
	iip_identy varchar(128),
	iip_wersja varchar(32),
	jpt_kj_iip varchar(20),
	jpt_kj_i_1 varchar(128),
	jpt_kj_i_2 varchar(32),
	jpt_opis varchar(254),
	jpt_sps_ko varchar(3),
	id_bufor_1 integer,
	jpt_id integer,
	jpt_kj_i_3 varchar(3),
	shape_leng numeric,
	shape_area numeric,
	geom geometry
)